# Generated by Django 5.2.5 on 2025-08-11 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_profile_options_alter_profile_bio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(verbose_name='Altura (cm)')),
                ('weight', models.FloatField(verbose_name='Peso (kg)')),
                ('date_of_birth', models.DateField(verbose_name='Data de Nascimento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=10, verbose_name='Gênero')),
                ('bf', models.FloatField(verbose_name='Percentual de Gordura Corporal')),
                ('bcm', models.FloatField(verbose_name='Massa Corporal Magra')),
                ('biceps_right', models.FloatField(verbose_name='Bíceps Direito (cm)')),
                ('biceps_left', models.FloatField(verbose_name='Bíceps Esquerdo (cm)')),
                ('anti_brachium_right', models.FloatField(verbose_name='Antebraço Direito (cm)')),
                ('anti_brachium_left', models.FloatField(verbose_name='Antebraço Esquerdo (cm)')),
                ('coxa_right', models.FloatField(verbose_name='Coxa Direita (cm)')),
                ('coxa_left', models.FloatField(verbose_name='Coxa Esquerda (cm)')),
                ('cintura', models.FloatField(verbose_name='Cintura (cm)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physical_assessment', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Avaliação Física',
                'verbose_name_plural': 'Avaliações Físicas',
            },
        ),
    ]
