# Generated by Django 5.2.5 on 2025-08-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_physicalassessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='level',
        ),
        migrations.AddField(
            model_name='profile',
            name='nivel',
            field=models.IntegerField(default=1, verbose_name='Nível'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.CharField(default='E', max_length=50, verbose_name='Rank'),
        ),
    ]
