# Generated by Django 5.2.5 on 2025-08-10 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Exercício')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('category', models.CharField(max_length=50, verbose_name='Categoria')),
                ('muscle_group', models.CharField(max_length=50, verbose_name='Grupo Muscular')),
            ],
            options={
                'verbose_name': 'Exercício',
                'verbose_name_plural': 'Exercícios',
            },
        ),
        migrations.CreateModel(
            name='BeginnerExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(default='Beginner', max_length=50, verbose_name='Dificuldade')),
                ('repetitions', models.IntegerField(default=6, verbose_name='Repetições')),
                ('sets', models.IntegerField(default=3, verbose_name='Séries')),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beginner_exercises', to='exercicios.exercise', verbose_name='Exercício Base')),
            ],
            options={
                'verbose_name': 'Exercício Iniciante',
                'verbose_name_plural': 'Exercícios Iniciantes',
            },
        ),
    ]
