# Generated by Django 5.2.5 on 2025-08-11 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beginnerexercise',
            name='exercise_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beginner_exercises', to='exercicios.exercise', verbose_name='Exercício'),
        ),
        migrations.CreateModel(
            name='IntermediateExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(default='Intermediate', max_length=50, verbose_name='Dificuldade')),
                ('repetitions', models.IntegerField(default=15, verbose_name='Repetições')),
                ('sets', models.IntegerField(default=5, verbose_name='Séries')),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intermediate_exercises', to='exercicios.exercise', verbose_name='Exercício')),
            ],
            options={
                'verbose_name': 'Exercício Intermediário',
                'verbose_name_plural': 'Exercícios Intermediários',
            },
        ),
    ]
