# Generated by Django 5.2.5 on 2025-08-11 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0002_alter_beginnerexercise_exercise_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(default='Advanced', max_length=50, verbose_name='Dificuldade')),
                ('repetitions', models.IntegerField(default=20, verbose_name='Repetições')),
                ('sets', models.IntegerField(default=6, verbose_name='Séries')),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advanced_exercises', to='exercicios.exercise', verbose_name='Exercício')),
            ],
            options={
                'verbose_name': 'Exercício Avançado',
                'verbose_name_plural': 'Exercícios Avançados',
            },
        ),
    ]
