# Generated by Django 5.2.5 on 2025-08-11 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0003_advancedexercise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalizedTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(default='Advanced', max_length=50, verbose_name='Dificuldade')),
                ('repetitions', models.IntegerField(default=0, verbose_name='Repetições')),
                ('sets', models.IntegerField(default=0, verbose_name='Séries')),
                ('exercises', models.ManyToManyField(to='exercicios.exercise', verbose_name='Exercícios')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalized_trainings', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Treino Personalizado',
                'verbose_name_plural': 'Treinos Personalizados',
            },
        ),
    ]
