# Generated by Django 5.2.5 on 2025-08-11 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0004_personalizedtraining'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=0, verbose_name='Duração (minutos/repetições)')),
                ('frequency', models.CharField(default='3 vezes por semana', max_length=50, verbose_name='Frequência')),
                ('exercises', models.ManyToManyField(to='exercicios.exercise', verbose_name='Exercícios')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Plano de Treino',
                'verbose_name_plural': 'Planos de Treino',
            },
        ),
    ]
